# Generated by Django 5.0.4 on 2024-05-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0004_alter_product_brand_alter_product_category_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
