# Generated by Django 5.0.4 on 2024-05-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_cart_items_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
