# Generated by Django 5.0.4 on 2024-05-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cartitem_quantity_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
