# Generated by Django 5.0.4 on 2024-05-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
