# Generated by Django 5.0.4 on 2024-05-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
