# Generated by Django 5.0.4 on 2024-05-15 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Adres Başlığı')),
                ('name_lastname', models.CharField(max_length=50, verbose_name='İsim ve Soyisim')),
                ('phoneNumber', models.CharField(max_length=10, verbose_name='Telefon Numarası')),
                ('eposta', models.EmailField(max_length=254, unique=True, verbose_name='E-Posta')),
                ('adres', models.TextField(max_length=264, verbose_name='Adres Bilgileri')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
