# Generated by Django 5.0.4 on 2024-05-15 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_adres_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='infos',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.adres'),
            preserve_default=False,
        ),
    ]
