# Generated by Django 5.0.4 on 2024-05-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='cargoNumber',
        ),
    ]
