# Generated by Django 5.0.4 on 2024-05-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_shipment_cargonumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='adres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.adres'),
        ),
    ]
