# Generated by Django 5.0.4 on 2024-05-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_adres_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='adresbilgileri',
            field=models.TextField(default=1, max_length=500, verbose_name='Adres Bilgileri'),
            preserve_default=False,
        ),
    ]
