# Generated by Django 5.0.4 on 2024-05-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_orderitem_adresbilgileri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='adresbilgileri',
            new_name='adres',
        ),
    ]
