# Generated by Django 5.0.4 on 2024-05-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_orderitem_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='adres',
            field=models.TextField(max_length=512, verbose_name='Adres Bilgileri'),
        ),
    ]
