# Generated by Django 5.0.4 on 2024-05-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_orderitem_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name_lastname',
            field=models.CharField(default='Varsayılan Ad Soyad', max_length=255, verbose_name='İsim Soyisim'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.TextField(default='Varsayılan Başlık', max_length=55, verbose_name='Adres Başlığı'),
        ),
    ]
