# Generated by Django 5.0.4 on 2024-05-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_orderitem_name_lastname_orderitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name_lastname',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='title',
        ),
        migrations.AddField(
            model_name='order',
            name='adres',
            field=models.TextField(default=1, max_length=512, verbose_name='Adres Bilgileri'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name_lastname',
            field=models.CharField(default='Varsayılan Ad Soyad', max_length=255, verbose_name='İsim Soyisim'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.TextField(default='Varsayılan Başlık', max_length=55, verbose_name='Adres Başlığı'),
        ),
    ]
