# Generated by Django 5.0.4 on 2024-05-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_remove_orderitem_adres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='adres',
        ),
    ]
